services:
  fuel-prices-api:
    image: ghcr.io/mjsully/fuel-prices-api
    user: 1000:1000
    container_name: fuel-prices-api
    ports:
      - 8000:8000
    volumes:
      - ./data/:/usr/src/app/data
    command: "uvicorn server:app --host 0.0.0.0"